Set the timezone as an environment variable.
AlexWinder/address-book pull request #6
Opened 2024-12-27 21:27 UTC by zaydons

Since I don't live in the `Europe/London` I thought it would be helpful to be able to change the timezone.

2024-12-28 02:45 UTC, zaydons commented
This works with Apache as the server.. Working on figuring out Nginx and Docker environments

2024-12-28 04:01 UTC, zaydons commented
[4f3b12b](https://github.com/AlexWinder/address-book/pull/6/commits/4f3b12b225dc2ff4b63fdde73474ecada3c6b143) Should handle the timezone variables a bit better. Worth noting that I haven't tested the Manual Nginx configuration since I don't have that setup readily available to test on. However Apache and Docker have been tested.

2025-01-01 21:30 UTC, AlexWinder requested changes
Thanks for the PR. I've made a few comments on a few things which I feel would improve it somewhat.

2025-01-01 21:30 UTC, AlexWinder commented on README.md
> +5. (OPTIONAL) To define a timezone orther than the default 'Europe/London', in your `docker-compose.yml` add the following under the 'php-fpm' service:
If it's included in the `settings.local.inc.php` file then there's no need to send it through in the Docker container.

2025-01-01 21:30 UTC, AlexWinder commented on README.md
> +#### Optional Configuration
I'd prefer not to include instructions relating to individual environments if possible. The README assumes that someone has a working web server with PHP - if custom timezone is to be configured with this then we leave it up to the user to know how to do this. It's the same reason why I don't have any instructions on how to configure Apache/Nginx to set this up.

2025-01-01 21:30 UTC, AlexWinder commented on includes/settings.config.inc.php
> + 	date_default_timezone_set(getenv('TZ'));
Does it need to use `getenv`? Can it not just call the constant directly?

2025-01-01 21:30 UTC, AlexWinder commented on includes/EXAMPLE.settings.local.inc.php
> +	defined("TZ")				?	null	:	define("TZ", "UTC");
`TZ` can be unclear, a better name might be `TIMEZONE`. Can you adjust to make the constant name more descriptive?

2025-01-03 01:36 UTC, zaydons commented on includes/settings.config.inc.php
> + 	date_default_timezone_set(getenv('TZ'));
Only needed the `genenv` when trying to support individual environments rather than just through Docker. This will be nixed in the next commit

2025-01-03 01:44 UTC, zaydons commented on README.md
> +#### Optional Configuration
agreed,

2025-01-03 01:50 UTC, zaydons commented
@AlexWinder Just did some updates for your review

2025-01-05 15:26 UTC, AlexWinder approved these changes
Works in Docker. Thanks for your changes @zaydons!

2025-01-05 15:26 UTC, merged